#!/usr/bin/env node

/**
 * Copyright 2017, Google, Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const spawn = require('child_process').spawn;
const path = require('path');

const version = require('../package.json').version;

const options = { stdio: 'inherit', shell: true };

function run (cmd, args) {
  return new Promise((resolve, reject) => {
    spawn(cmd, args, options).on('exit', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject();
      }
    });
  });
}

run('pkg', ['.', '--out-path', 'binaries'])
  .then(() => run('gsutil', ['cp', 'binaries/*', `gs://cloud-docs-samples/releases/${version}/`]))
  .then(() => run('gsutil', ['acl', 'ch', '-u', 'AllUsers:R', `gs://cloud-docs-samples/releases/${version}/*`]))
  .then(() => run('gsutil', ['cp', `gs://cloud-docs-samples/releases/${version}/*`, 'gs://cloud-docs-samples/releases/latest/']))
  .then(() => run('gsutil', ['acl', 'ch', '-u', 'AllUsers:R', 'gs://cloud-docs-samples/releases/latest/*']))
  .catch(console.error);
